services:
  nginx-proxy:
    volumes:
      - ../crm-dashboard:/opt/crm-dashboard:ro
      - ./nginx/crm-dashboard.conf:/etc/nginx/conf.d/crm-dashboard.conf:ro
    ports:
      - 80:80
      - 443:443

  moqui-server:
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - ../backend/data:/opt/moqui/runtime/component/growerp/data
      - ../backend/service:/opt/moqui/runtime/component/growerp/service
    environment:
      - DB_DATA=INSTALL
      - webapp_https_enabled=false
