// ── Segment color map ──
const SEGMENT_COLORS = {
  agro:       { bg: '#0d4f1c', accent: '#2ecc71', light: '#d5f5e3', tag: '🌾' },
  agents:     { bg: '#1a1a40', accent: '#8e44ad', light: '#e8d5f5', tag: '🤖' },
  enterprise: { bg: '#0c3547', accent: '#2980b9', light: '#d4e6f1', tag: '🏢' },
  business:   { bg: '#4a2600', accent: '#e67e22', light: '#fdebd0', tag: '💼' },
  franquia:   { bg: '#4a0026', accent: '#e74c3c', light: '#fadbd8', tag: '🏪' },
  solucoes:   { bg: '#3b3b00', accent: '#f1c40f', light: '#fef9e7', tag: '🎯' },
};

// ── Personas ──
const PERSONAS = [
  {
    id: 'BLAH_PERSONA_AGRO',
    segment: 'agro',
    name: 'Agronegocio Decision Maker',
    demographics: 'Owners and managers of agribusiness operations that need clearer lead flow, follow-up, and conversion tracking.',
    painPoints: 'Disorganized lead intake, slow response times, manual WhatsApp follow-up, and weak attribution between campaigns and sales.',
    goals: 'Capture qualified leads faster, route them to the right segment page, and keep every follow-up measurable.',
    tone: 'Direct, practical, operational, and focused on profit and speed.',
  },
  {
    id: 'BLAH_PERSONA_AGENTS',
    segment: 'agents',
    name: 'Agency Growth Lead',
    demographics: 'Owners and operators of lead generation agencies that need repeatable delivery and visible pipeline health.',
    painPoints: 'Campaign chaos, duplicated contacts, inconsistent messaging, and no clear separation between clients or squads.',
    goals: 'Standardize outreach, keep tenants isolated, and present clear next steps for every prospect.',
    tone: 'Professional, concise, and performance-oriented.',
  },
  {
    id: 'BLAH_PERSONA_ENTERPRISE',
    segment: 'enterprise',
    name: 'Enterprise Revenue Operations',
    demographics: 'Enterprise teams that require governance, segmentation, and predictable reporting across channels.',
    painPoints: 'Fragmented workflows, manual data hygiene, and poor visibility into campaign performance.',
    goals: 'Create controlled landing pages, segment-specific journeys, and auditable activity histories.',
    tone: 'Structured, confident, and evidence-driven.',
  },
  {
    id: 'BLAH_PERSONA_BUSINESS',
    segment: 'business',
    name: 'SMB Business Owner',
    demographics: 'Small and mid-sized business owners that need a clear, low-friction CRM entry point.',
    painPoints: 'Too many tools, little consistency, and no clean handoff from lead to opportunity.',
    goals: 'Get a simple path from form submission to follow-up with measurable outcomes.',
    tone: 'Friendly, clear, and outcome-focused.',
  },
  {
    id: 'BLAH_PERSONA_FRANQUIA',
    segment: 'franquia',
    name: 'Franchise Expansion Lead',
    demographics: 'Franchise owners and expansion managers who need consistent messaging and distributed lead handling.',
    painPoints: 'Hard to keep brand consistency across units, difficult to track inquiries, and slow qualification.',
    goals: 'Unify the funnel, split by region or segment, and keep every inquiry traceable.',
    tone: 'Clear, practical, and scalable.',
  },
  {
    id: 'BLAH_PERSONA_SOLUCOES',
    segment: 'solucoes',
    name: 'Solutions Buyer',
    demographics: 'Decision makers searching for specific solutions and wanting a direct next step.',
    painPoints: 'Generic pitches, unclear value propositions, and landing pages that do not match intent.',
    goals: 'Match content to intent, route leads by segment, and present a short conversion path.',
    tone: 'Concise, helpful, and solution-oriented.',
  },
];

// ── Landing Pages ──
const LANDING_PAGES = [
  {
    id: 'BLAH_LP_AGRO',
    segment: 'agro',
    title: 'Agronegocio | Blah Software',
    headline: 'More qualified agribusiness leads, with follow-up that does not get lost.',
    subheading: 'A dedicated page for agribusiness visitors, with a short path to WhatsApp and e-mail contact, backed by clear routing and measurement.',
    url: 'https://agronegocio.blahsoftware.ia.br',
    status: 'ACTIVE',
    hookType: 'results',
    sections: [
      { title: 'Why agribusiness leads get lost', desc: 'This page captures the main agribusiness pain points: slow response, scattered contact history, and weak attribution.' },
      { title: 'Fast follow-up path', desc: 'Lead into a short WhatsApp or e-mail follow-up that is easy to measure inside the CRM.' },
    ],
    credibility: 'Blah Software combines CRM structure, segmentation, and automation to help agribusiness teams keep pace with demand.',
    stats: ['Faster response times reduce lead drop-off.', 'Segment-specific pages improve campaign attribution.'],
  },
  {
    id: 'BLAH_LP_AGENTS',
    segment: 'agents',
    title: 'Agents | Blah Software',
    headline: 'Segmented outreach for agencies that need clean delivery and clean reporting.',
    subheading: 'A landing page designed for agencies, with separate journeys for each audience and an easier handoff into CRM.',
    url: 'https://agents.blahsoftware.com.br',
    status: 'ACTIVE',
    hookType: 'problem',
    sections: [
      { title: 'Agency delivery control', desc: 'Agencies need separate journeys for different audiences, with less duplication and more visibility.' },
      { title: 'Segmented handoff', desc: 'Each lead is routed to the right owner, so the team can follow up without mixing client data.' },
    ],
    credibility: 'Agency teams use the same CRM backbone to keep client data isolated and delivery measurable.',
    stats: ['Structured follow-up reduces duplicated contact effort.', 'Tenant separation keeps client work auditable.'],
  },
  {
    id: 'BLAH_LP_ENTERPRISE',
    segment: 'enterprise',
    title: 'Enterprise | Blah Software',
    headline: 'Governed, auditable segment pages for enterprise demand generation.',
    subheading: 'Built for teams that need a controlled funnel, consistent messaging, and traceable pipeline attribution.',
    url: 'https://enterprise.blahsoftware.ia.br',
    status: 'ACTIVE',
    hookType: 'results',
    sections: [
      { title: 'Controlled demand generation', desc: 'Enterprise teams get a governed path from campaign entry to CRM record creation.' },
      { title: 'Audit-friendly journey', desc: 'The messaging sequence stays short, explicit, and traceable for reporting.' },
    ],
    credibility: 'Enterprise workflows need clear governance, simple routing, and audit-friendly messaging.',
    stats: ['Controlled journeys reduce noise in enterprise pipelines.', 'Clear audit trails improve internal confidence.'],
  },
  {
    id: 'BLAH_LP_BUSINESS',
    segment: 'business',
    title: 'Business | Blah Software',
    headline: 'A simple CRM path for businesses that want more response and less manual work.',
    subheading: 'This page keeps the journey short: interest, contact, qualification, and follow-up.',
    url: 'https://business.blahsoftware.ia.br',
    status: 'ACTIVE',
    hookType: 'problem',
    sections: [
      { title: 'Low-friction CRM entry', desc: 'Designed for businesses that want to capture interest and move quickly to qualification.' },
      { title: 'Clear next step', desc: 'The visitor sees one simple next action instead of a long or noisy flow.' },
    ],
    credibility: 'Small and mid-sized businesses benefit from a short, direct path into CRM and follow-up.',
    stats: ['Short forms usually convert better than noisy journeys.', 'Clear CTAs improve the handoff into the CRM.'],
  },
  {
    id: 'BLAH_LP_FRANQUIA',
    segment: 'franquia',
    title: 'Franquia | Blah Software',
    headline: 'Standardize franchise inquiries without losing local context.',
    subheading: 'A page built for franchise expansion, regional routing, and consistent follow-up across units.',
    url: 'https://franquia.blahsoftware.ia.br',
    status: 'ACTIVE',
    hookType: 'results',
    sections: [
      { title: 'Consistent franchise messaging', desc: 'Franchises need a repeatable pitch that still respects regional context.' },
      { title: 'Local routing, central control', desc: 'Every lead is routed cleanly while the main team keeps reporting and governance.' },
    ],
    credibility: 'Franchise operations need consistent messaging with local routing and central control.',
    stats: ['Central control keeps franchise messaging consistent.', 'Local routing keeps leads close to the right unit.'],
  },
  {
    id: 'BLAH_LP_SOLUCOES',
    segment: 'solucoes',
    title: 'Solucoes | Blah Software',
    headline: 'Route each intent to the right message, page, and follow-up.',
    subheading: 'A practical entry point for visitors who already know the category they need and want a direct answer.',
    url: 'https://solucoes.blahsoftware.ia.br',
    status: 'ACTIVE',
    hookType: 'results',
    sections: [
      { title: 'Match intent to solution', desc: 'Visitors who already know what they want should see a direct path, not a generic pitch.' },
      { title: 'Short path to contact', desc: 'The page keeps the journey short and focused on conversion.' },
    ],
    credibility: 'Solution-led pages work best when intent, message, and next action are aligned.',
    stats: ['Intent-matched pages usually convert better.', 'A short funnel reduces friction.'],
  },
];

// ── Campaigns ──
const CAMPAIGNS = [
  {
    id: 'BLAH_CAMP_AGRO',
    segment: 'agro',
    name: 'Blah Agro — WhatsApp and Email',
    summary: 'Segmented outreach for agribusiness buyers with a dedicated landing page.',
    platforms: ['EMAIL', 'WHATSAPP'],
    audience: 'Agribusiness owners, managers, and commercial leads',
    landingPage: 'BLAH_LP_AGRO',
    whatsappMsg: 'Oi {{firstName}}, criamos uma pagina focada em agronegocio para reduzir perda de leads e organizar o follow-up.',
    emailSubject: 'Agronegocio: sua nova pagina de conversao',
    emailCta: 'https://agronegocio.blahsoftware.ia.br',
    whatsappShort: 'Mensagem curta, direta e personalizada para agronegocio.',
    status: 'PLANNED',
    dailyLimit: 25,
  },
  {
    id: 'BLAH_CAMP_AGENTS',
    segment: 'agents',
    name: 'Blah Agents — WhatsApp and Email',
    summary: 'Agency outreach with client isolation and a dedicated landing path.',
    platforms: ['EMAIL', 'WHATSAPP'],
    audience: 'Agency owners and operations leads',
    landingPage: 'BLAH_LP_AGENTS',
    whatsappMsg: 'Oi {{firstName}}, sua agencia pode trabalhar com paginas separadas por segmento e com follow-up rastreavel.',
    emailSubject: 'Agencia: pagina segmentada para sua operacao',
    emailCta: 'https://agents.blahsoftware.com.br',
    whatsappShort: 'Mensagem curta para agencias e squads.',
    status: 'PLANNED',
    dailyLimit: 25,
  },
  {
    id: 'BLAH_CAMP_ENTERPRISE',
    segment: 'enterprise',
    name: 'Blah Enterprise — WhatsApp and Email',
    summary: 'Enterprise demand generation with governance and audit-friendly copy.',
    platforms: ['EMAIL', 'WHATSAPP'],
    audience: 'Enterprise revenue operations and commercial teams',
    landingPage: 'BLAH_LP_ENTERPRISE',
    whatsappMsg: 'Oi {{firstName}}, montamos um fluxo com pagina segmentada e trilha clara para o time comercial.',
    emailSubject: 'Enterprise: fluxo segmentado e auditavel',
    emailCta: 'https://enterprise.blahsoftware.ia.br',
    whatsappShort: 'Mensagem objetiva para enterprise.',
    status: 'PLANNED',
    dailyLimit: 25,
  },
  {
    id: 'BLAH_CAMP_BUSINESS',
    segment: 'business',
    name: 'Blah Business — WhatsApp and Email',
    summary: 'Small business entry flow with a short route from interest to contact.',
    platforms: ['EMAIL', 'WHATSAPP'],
    audience: 'SMB owners and operators',
    landingPage: 'BLAH_LP_BUSINESS',
    whatsappMsg: 'Oi {{firstName}}, deixamos seu caminho mais simples para capturar contatos e responder mais rapido.',
    emailSubject: 'Business: menos friccao, mais respostas',
    emailCta: 'https://business.blahsoftware.ia.br',
    whatsappShort: 'Mensagem curta para SMB.',
    status: 'PLANNED',
    dailyLimit: 25,
  },
  {
    id: 'BLAH_CAMP_FRANQUIA',
    segment: 'franquia',
    name: 'Blah Franquia — WhatsApp and Email',
    summary: 'Franchise expansion with local routing and centralized visibility.',
    platforms: ['EMAIL', 'WHATSAPP'],
    audience: 'Franchise expansion managers',
    landingPage: 'BLAH_LP_FRANQUIA',
    whatsappMsg: 'Oi {{firstName}}, sua franquia pode centralizar o funil sem perder o contexto local.',
    emailSubject: 'Franquia: funil central e local ao mesmo tempo',
    emailCta: 'https://franquia.blahsoftware.ia.br',
    whatsappShort: 'Mensagem curta para franquias.',
    status: 'PLANNED',
    dailyLimit: 25,
  },
  {
    id: 'BLAH_CAMP_SOLUCOES',
    segment: 'solucoes',
    name: 'Blah Solucoes — WhatsApp and Email',
    summary: 'Solution-led page with a direct message and a clean conversion path.',
    platforms: ['EMAIL', 'WHATSAPP'],
    audience: 'Intent-led buyers',
    landingPage: 'BLAH_LP_SOLUCOES',
    whatsappMsg: 'Oi {{firstName}}, se voce ja sabe o que precisa, esta pagina leva direto ao contato certo.',
    emailSubject: 'Solucoes: caminho direto para conversao',
    emailCta: 'https://solucoes.blahsoftware.ia.br',
    whatsappShort: 'Mensagem curta para intent/solucoes.',
    status: 'PLANNED',
    dailyLimit: 25,
  },
];

// ── Observability Mock Data ──
const OBSERVABILITY_DATA = {
  infra: {
    vpn: { status: 'ONLINE', latency: '45ms', uptime: '99.9%' },
    ssh: { status: 'SECURE', activeConnections: 3, lastAudit: '10 min ago' },
    network: { status: 'STABLE', queueSize: 12, throughput: '150 req/s' },
  },
  queues: [
    { name: 'Q-AGRO-WHATSAPP', channel: 'WhatsApp', processed: 450, pending: 12, status: 'HEALTHY' },
    { name: 'Q-AGENTS-EMAIL', channel: 'Email', processed: 1200, pending: 5, status: 'HEALTHY' },
    { name: 'Q-ENTERPRISE-MIX', channel: 'Omni', processed: 890, pending: 45, status: 'WARNING' },
    { name: 'Q-BUSINESS-WHATSAPP', channel: 'WhatsApp', processed: 320, pending: 0, status: 'IDLE' },
  ],
  agents: [
    { name: 'Agent-Agro-Sender', segment: 'agro', task: 'Disparo WA', uptime: '4h 12m', status: 'RUNNING' },
    { name: 'Agent-Agents-Mail', segment: 'agents', task: 'Disparo Email', uptime: '12h 0m', status: 'RUNNING' },
    { name: 'Agent-Ent-Router', segment: 'enterprise', task: 'Roteamento', uptime: '1d 4h', status: 'RUNNING' },
    { name: 'Agent-Bus-Sync', segment: 'business', task: 'Sincronização CRM', uptime: '5m', status: 'RESTARTING' },
  ]
};
